server:
  port: 8082
service-rabbit:
  exchangeReceiverName: Planner
  vk-routing-key: vk;
  telegram-routing-key: telegram
  youtube-routing-key: youtube
  exchange-sender-name: Sender
  telegram-crawler-queue-name: Crawler1
  vk-crawler-queue-name: Crawler2
  youtube-crawler-queue-name: Crawler3
db:
  url: jdbc:postgresql://localhost:5432/AgonaSemester-db
  username: postgres
  password: postgres
  driver-classname: org.postgresql.Driver
  pool-size: 10
spring:
  rabbitmq:
    host: localhost
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/AgonaSemester-db
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: postgres