version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9.5-management
    restart: on-failure
    ports:
      - 5672:5672
      - 15672:15672
  Orc-db:
    container_name: db
    image: postgres:12-alpine
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db